create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) <= 12),
  score integer not null,
  max_combo integer not null,
  bpm integer not null,
  speed numeric(4, 2) not null,
  mode text not null,
  full_combo boolean not null default false,
  judgements jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists scores_score_desc_idx
  on public.scores (score desc);

alter table public.scores enable row level security;

drop policy if exists "scores are readable by everyone" on public.scores;
create policy "scores are readable by everyone"
  on public.scores
  for select
  using (true);

drop policy if exists "scores are insertable by everyone" on public.scores;
create policy "scores are insertable by everyone"
  on public.scores
  for insert
  with check (true);
